server:
  port: 4240

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:4241
              predicates:
                - Path=/api/users/**

            - id: order-service
              uri: http://localhost:4242
              predicates:
                - Path=/api/orders/**
