server:
  port: 4240

spring:
  datasource:
    url: jdbc:h2:mem:userdb
#    url: jdbc:h2:file:./data/userdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 332003
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
